CREATE TABLE correlation_temp 
( row_names TEXT,
	Cluster_ORF_1 TEXT,
	Type TEXT,
	Cluster_ORF_2 TEXT,
	Correlation REAL,
	Min_Z_Score_1_2 REAL,
	Min_NegLog_FDR_1_2 REAL,
	Z_Score_Gene1 REAL,
	Z_Score_Gene2 REAL,
	NegLog_Pval_Gene1 REAL,
	NegLog_FDR_Gene1 REAL,
	NegLog_Pval_Gene2 REAL,
	NegLog_FDR_Gene2 REAL,
	Self INTEGER,
	Systematic_name_pair TEXT,
	Common_name_pair TEXT,
	Systematic_name1 TEXT,
	Common_name1 TEXT,
	Viability1 TEXT,
	Systematic_name2 TEXT,
	Common_name2 TEXT,
	Viability2 TEXT 
)